### ISSUE TITLE
可以出一个用OneDrive做存储的方法吗

### ISSUE THREAD

**Issue by clonek** [Rr210/blazeB2#10]
OneDrive要比back blaze大多了 存的图片也可以更多

**Comment by Suyuqu** [comment]
这是Backblaze的[官方文档](https://www.backblaze.com/b2/docs)对于Backblaze B2 Cloud Storage的概念
>Backblaze B2 is simple, reliable, affordable object storage. Each account gets 10 GB of free storage, unlimited free uploads, and 1 GB of free downloads each day. There are no hidden fees. See the [Pricing](https://www.backblaze.com/b2/cloud-storage-pricing.html) page for details.

>To use B2 Cloud Storage, you need to have a Backblaze account. You may create an account by signing up at [backblaze.com](https://www.backblaze.com/). After enabling Backblaze B2 for your account, you will have access to your Application Key Id and Application Key that let you call the APIs.

>Backblaze supports two different suites of APIs: [S3 Compatible](https://www.backblaze.com/b2/docs/s3_compatible_api.html) and B2 Native. We generally recommend that developers use the S3 Compatible API when writing new applications and integrations, as it is supported by a wider range of SDKs and libraries, and many developers already have experience with Amazon S3. You can use the Backblaze B2 web console or the B2 Native API to access functionality, such as application key management and lifecycle rules, that is not covered by the S3 Compatible API.

>Take a look at the Backblaze [B2 Native Quick Start Guide](https://www.backblaze.com/b2/docs/quick_account.html) and [Backblaze B2 Quick Start: Using Python With the Backblaze S3 Compatible API](https://www.backblaze.com/b2/docs/python.html) to get started right away.

>Using the Backblaze APIs, you can:

>Upload, download, and delete files
Create and manage the buckets that hold files
Manage the configuration of your account*
>* Backblaze B2 Native APIs only

我把最主要的翻译给你看，就是第一段
>Backblaze B2是一种简单、可靠、价格合理的对象存储。每个帐户每天获得10 GB的免费存储空间、无限的免费上传和1 GB的免费下载。

这两个的储存概念就不是一样的，要是硬比较的话，没多少人会一天上传10GB的图片吧，所以应该是Backblaze B2的存储大于OneDrive。再说你是用的OneDrive是个人版，还是企业版，个人版已经被墙了，企业版你还有考虑开发者到期的时间，而这一个桶却是永久的。

**Comment by clonek** [comment]
感谢解答
