### ISSUE TITLE
这一步的设置入口 我找不到啊

### ISSUE THREAD

**Issue by wgx-dh** [Rr210/blazeB2#2]
![image](https://user-images.githubusercontent.com/63238251/180632660-89a9e472-8758-4591-b595-8959443cc2c4.png)
是这个？
![image](https://user-images.githubusercontent.com/63238251/180632705-dfbb4873-957e-4f32-93db-185eb1e82dbc.png)
还是这个？
![image](https://user-images.githubusercontent.com/63238251/180632730-f7272539-f60d-4f55-b589-3984c0cb1837.png)

**Comment by ryanuo** [comment]
![](https://cloud.mr90.top/hexo/5/fd196f78-9412-47de-b4cb-e0943ccadf65.png)

**Comment by ryanuo** [comment]
> ![image](https://user-images.githubusercontent.com/63238251/180632660-89a9e472-8758-4591-b595-8959443cc2c4.png) 是这个？ ![image](https://user-images.githubusercontent.com/63238251/180632705-dfbb4873-957e-4f32-93db-185eb1e82dbc.png) 还是这个？ ![image](https://user-images.githubusercontent.com/63238251/180632730-f7272539-f60d-4f55-b589-3984c0cb1837.png)

页面规则

**Comment by ryanuo** [comment]
您好，是否解决？如果解决我将关闭该issue🎃
