### ISSUE TITLE
网页bug

### ISSUE THREAD

**Issue by hearthitagi** [Rr210/blazeB2#26]
![image](https://user-images.githubusercontent.com/83416709/201487277-2c1b3cb4-5485-4194-9e6e-a6edea3be0eb.png)

![image](https://user-images.githubusercontent.com/83416709/201487320-4e047f46-74e3-4014-a8ec-fcac2b1b3f5e.png)

图片上传的时候和图床管理底部超出了，没有滚动条，调整一下？

**Comment by recreyed** [comment]
应该是footer的fix定位的问题
