### ISSUE TITLE
在CF规则中无法重定向到桶

### ISSUE THREAD

**Issue by Suyuqu** [Rr210/blazeB2#7]
![image](https://imgcdn.simsoft.top/1658824097-image.png)

如图所示，我在配置好规则后，无法触发第二条。

**Comment by Suyuqu** [comment]
![image](https://imgcdn.simsoft.top/1658824360-image.png)

图片一直是显示加载中
![image](https://imgcdn.simsoft.top/1658824429-image.png)

复制链接打开后显示不存在，但是我在blaze的桶中看到了文件，也就是说上传图片是正常的，无法显示图片

控制台查看无法加载的图片地址

**Comment by ryanuo** [comment]
第三条删除
配置url重写[这里](https://blazeb2.js.org/zh/guide/#%E9%87%8D%E5%86%99url)

**Comment by ryanuo** [comment]
> 控制台查看无法加载的图片地址

**Comment by Suyuqu** [comment]
> 第三条删除 配置url重写[这里](https://blazeb2.js.org/zh/guide/#%E9%87%8D%E5%86%99url)

第三条删除那就无法用CF加速Vercel了，在vercel上就无法自定义域名了

**Comment by Suyuqu** [comment]
> 

https://img.admirelight.com/file/imagesbucket/img/e56b4e13-c966-4671-b412-52603b7f8c7f.png

**Comment by ryanuo** [comment]
> > 第三条删除 配置url重写[这里](https://blazeb2.js.org/zh/guide/#%E9%87%8D%E5%86%99url)
> 
> 第三条删除那就无法用CF加速Vercel了，在vercel上就无法自定义域名了

换一个二级域名去自定义vercel *img 换成其他的

**Comment by Suyuqu** [comment]
> > > 第三条删除 配置url重写[这里](https://blazeb2.js.org/zh/guide/#%E9%87%8D%E5%86%99url)
> > 
> > 
> > 第三条删除那就无法用CF加速Vercel了，在vercel上就无法自定义域名了
> 
> 换一个二级域名去自定义vercel *img 换成其他的

应该不是域名的问题吧，还有第二条中桶后面的$1是什么

**Comment by Suyuqu** [comment]
求求了，出个视频教程吧，我给你投两个币[doge

**Comment by ryanuo** [comment]
> 应该不是域名的问题吧，还有第二条中桶后面的$1是什么

$1 泛指你请求的其他地址；
你vercel的自定义域名地址 要和那个图床的地址区别开  两个域名地址哇

**Comment by ryanuo** [comment]
> 求求了，出个视频教程吧，我给你投两个币[doge

你的vercel自定义域名地址是啥 确定都配置上了？DNS配置了吗？

**Comment by Suyuqu** [comment]
> > 应该不是域名的问题吧，还有第二条中桶后面的$1是什么
> 
> $1 泛指你请求的其他地址； 你vercel的自定义域名地址 要和那个图床的地址区别开 两个域名地址哇

现在vercel部署的地址是http://pic.admirelight.com/
那配置管理里面呢

**Comment by Suyuqu** [comment]
> > 求求了，出个视频教程吧，我给你投两个币[doge
> 
> 你的vercel自定义域名地址是啥 确定都配置上了？DNS配置了吗？

确定都配置了不过DNS里面我配置的链接是vercel里面的项目而不是桶
一开始是http://img.admirelight.com/
应你的要求改成了http://pic.admirelight.com/

**Comment by ryanuo** [comment]
> > > 求求了，出个视频教程吧，我给你投两个币[doge
> > 
> > 
> > 你的vercel自定义域名地址是啥 确定都配置上了？DNS配置了吗？
> 
> 确定都配置了不过DNS里面我配置的链接是vercel里面的项目而不是桶 一开始是http://img.admirelight.com/ 应你的要求改成了http://pic.admirelight.com/

好的配置完成 应该是没什么问题了

**Comment by ryanuo** [comment]
![image](https://user-images.githubusercontent.com/66169324/180967958-7159f029-c4fb-4678-a621-73eba1da3f0e.png)

**Comment by Suyuqu** [comment]
> ![image](https://user-images.githubusercontent.com/66169324/180967958-7159f029-c4fb-4678-a621-73eba1da3f0e.png)

在你的文档中
https://cloud.mr90.top/hexo/4/1501d938-a4e2-47c2-a2ee-b49169e3e487.png
这个DNS是什么

**Comment by Rr210** [comment]
图床的呀

**Comment by Rr210** [comment]
我的图床域名地址：cloud.mr90.top  将backblazeb2提供的cname 在cloudflare上进行DNS配置
vercel域名地址：blazeb2.mr90.cf   我是将主域名的域名服务商 改为vercel 没有走cloudflare

**Comment by ryanuo** [comment]
是否成功解决，如果解决 我将关闭该issues 
感谢您的使用 我会将您的问题加入到常见问题中
欢迎issues 🎃

**Comment by Admirelight** [comment]
> backblazeb2提供的cname

backblazeb2提供cname？你是不是隐瞒了步骤

**Comment by ryanuo** [comment]
> > backblazeb2提供的cname
> 
> backblazeb2提供cname？你是不是隐瞒了步骤

没有啊 就是[这](https://blazeb2.js.org/zh/guide/#%E6%9F%A5%E7%9C%8Bb2%E6%A1%B6%E5%9F%9F%E5%90%8D)

**Comment by Admirelight** [comment]
> 我的图床域名地址：cloud.mr90.top 将backblazeb2提供的cname 在cloudflare上进行DNS配置
vercel域名地址：blazeb2.mr90.cf 我是将主域名的域名服务商 改为vercel 没有走cloudflare

我坐了超市门口的摇摇车摇了两个小时还没摇明白你这逻辑[doge

**Comment by Rr210** [comment]
> > 我的图床域名地址：cloud.mr90.top 将backblazeb2提供的cname 在cloudflare上进行DNS配置
> > vercel域名地址：blazeb2.mr90.cf 我是将主域名的域名服务商 改为vercel 没有走cloudflare
> 
> 我坐了超市门口的摇摇车摇了两个小时还没摇明白你这逻辑[doge

文档很清楚 按照步骤 一步一步来
我这上面说的不是很清楚吗 是哪里说错了吗

**Comment by Admirelight** [comment]
> > > 我的图床域名地址：cloud.mr90.top 将backblazeb2提供的cname 在cloudflare上进行DNS配置
> > > vercel域名地址：blazeb2.mr90.cf 我是将主域名的域名服务商 改为vercel 没有走cloudflare
> > 
> > 
> > 我坐了超市门口的摇摇车摇了两个小时还没摇明白你这逻辑[doge
> 
> 文档很清楚 按照步骤 一步一步来 我这上面说的不是很清楚吗 是哪里说错了吗
> 
> 我上面是两个域名哦 一个.cf的 一个.top的 *.cf域名没有托管cloudflare .top 是托管在cloudflare

容我再试试o(╥﹏╥)o

**Comment by Rr210** [comment]
1577791638 这是qq 我看看你的这个配置
